name: Deploy Next.js (Self-Hosted VM)

on:
  push:
    branches:
      - main  # main branch push pe deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Node & NPM PATH
        # Yeh step PATH set kar dega taaki runner npm/pm2 recognize kare
        run: |
          echo "export PATH=$PATH:/home/develop_admin_vm/.nvm/versions/node/$(node -v)/bin" >> $GITHUB_ENV

      - name: Sync code to app folder
        run: |
          rsync -av --delete ./ /var/www/nextapp/

      - name: Install dependencies
        run: |
          cd /var/www/nextapp
          npm install

      - name: Build Next.js
        run: |
          cd /var/www/nextapp
          npm run build

      - name: Start or restart app with PM2
        run: |
          cd /var/www/nextapp
          pm2 restart nextapp || pm2 start npm --name nextapp -- start
