name: Deploy Next.js (Self-Hosted VM)

on:
  push:
    branches:
      - main  # main branch push pe deploy

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync code to app folder
        run: |
          rsync -av --delete ./ /var/www/nextapp/

      - name: Install dependencies
        run: |
          cd /var/www/nextapp
          /home/develop_admin_vm/.nvm/versions/node/v18.17.1/bin/npm install

      - name: Build Next.js
        run: |
          cd /var/www/nextapp
          /home/develop_admin_vm/.nvm/versions/node/v18.17.1/bin/npm run build

      - name: Start or restart app with PM2
        run: |
          cd /var/www/nextapp
          /home/develop_admin_vm/.nvm/versions/node/v18.17.1/bin/pm2 restart nextapp || /home/develop_admin_vm/.nvm/versions/node/v18.17.1/bin/pm2 start /home/develop_admin_vm/.nvm/versions/node/v18.17.1/bin/npm --name nextapp -- start
